name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy pytest typer pydantic
      - name: Format
        run: black --check --preview .
      - name: Lint
        run: ruff check .
      - name: Typecheck
        run: mypy .
      - name: Test
        run: pytest -q
