name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v4
      - name: Install dependencies
        run: uv pip install --system -e .
      - name: Format
        run: uv run black --check --preview .
      - name: Lint
        run: uv run ruff check .
      - name: Typecheck
        run: uv run mypy .
      - name: Test
        run: uv run pytest -q
